[package]
name = "dichtdelicht-rust-controller"
version = "0.1.0"
authors = ["Sander Steeghs <sander@steeghs.info>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
firestore_grpc = "0.1.1"
grpcio = "0.5.3"